WebApplication1/Controllers/THM104Controller.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Differencing;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Timers;
using WebApplication1.Filters;
using WebApplication1.Models;
using WebApplication1.Models.Entity;

namespace WebApplication1.Controllers
{
    public class THM104Controller : Controller
    {
        private readonly NorthwindContext _db;
        private readonly IWebHostEnvironment _env;
        private readonly ILogger<THM104Controller> _logger;

        public THM104Controller(NorthwindContext db, IWebHostEnvironment env,ILogger<THM104Controller> logger)
        {
            _db = db;
            _env = env;
            _logger = logger;
        }

        public IActionResult Delete(int id)
        {
            var student = _db.Stuednts.FirstOrDefault(x => x.Id == id);
            if (student != null)
            {
                _db.Stuednts.Remove(student);
                _db.SaveChanges();
            }
            return RedirectToAction("students");
        }


        public IActionResult Edit(int id) 
        {
            var result = _db.Stuednts.FirstOrDefault(x => x.Id == id);
            if (result == null)
            {
                return RedirectToAction("students");
            }
            var data = new EditViewModel()
            {
                Id = id,
                Email = result.Email,
                Gender = result.Gender,
                Name = result.Name,
                Password = result.Password,                
                Phone = result.Phone,
                Path = result.PicturePath               
            };
            ViewBag.GenderEnum = Enum.GetValues(typeof(GenderEnum)).Cast<GenderEnum>().Select(se => new SelectListItem
            {
                Text = se.ToString(),
                Value = ((int)se).ToString()
            });

            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(EditViewModel model)
        {
            var student = _db.Stuednts.FirstOrDefault(x => x.Id == model.Id);
            if (student == null) return View(model);

            var relativePath = "";
            if (model.File != null)
            {
                //C:\Users\T14 Gen 3\source\repos\WebApplication1\WebApplication1\wwwroot\pic\
                var dir = $"{_env.WebRootPath}";
                //354535-3425435-225-234_2.jpeg
                relativePath = $"/pic/{Guid.NewGuid()}_{model.File.FileName}";


                using (var fs = new FileStream(dir + relativePath, FileMode.Create))
                {
                    model.File.CopyTo(fs);
                }
            }

            student.Email = model.Email;
            student.Gender = model.Gender;
            student.Name = model.Name;
            student.Password = model.Password;
            student.Phone = model.Phone;
            if (!string.IsNullOrEmpty(relativePath))
            {
                student.PicturePath = relativePath;
            }
           

            _db.SaveChanges();
            


            return RedirectToAction("students");
        }
        [ServiceFilter(typeof(TimerActionFilter))]
        public IActionResult Students()
        {
           
            _logger.LogWarning("還敢偷看女學生");
            var result= _db.Stuednts.Select(x => new StudentsViewModel
            {
                Email = x.Email,
                Gender = x.Gender,
                Id = x.Id,
                Name = x.Name,
                Phone = x.Phone,
                PicturePath = x.PicturePath,
            }).ToList();

            _logger.LogWarning("還敢偷看女學生",result);
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> DownloadPdf()
        {
            var fileName = "1122選課須知.pdf";
            var fullpath = $"{_env.WebRootPath}/Pdf/{fileName}";

            var fillBytes = await System.IO.File.ReadAllBytesAsync(fullpath);

            return File(fillBytes, "application/pdf");
        }

        [Authorize(Roles ="Admin")]
        public IActionResult CustomersDisplay()
        {
            _logger.LogDebug("偷偷看CustomersDisplay");
            var result = _db.Customers.Select(x => new CustomersDisplayViewModel
            {
                Phone = x.Phone,
                Address = x.Address,
                City = x.City,
                PostalCode = x.PostalCode,
                Country = x.Country,
                CompanyName = x.CompanyName,
                ContactName = x.ContactName,
                ContactTitle = x.ContactTitle,
                CustomerId = x.CustomerId,
                Fax = x.Fax,
                Region = x.Region,
            }).ToList();
            return View(result);
        }

        public IActionResult Register()
        {
            ViewBag.GenderEnum = Enum.GetValues(typeof(GenderEnum)).Cast<GenderEnum>().Select(se => new SelectListItem
            {
                Text = se.ToString(),
                Value = ((int)se).ToString()
            });

            return View();
        }
        [HttpPost]
        public IActionResult Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var relativePath = "";
            if (model.File != null)
            {
                //C:\Users\T14 Gen 3\source\repos\WebApplication1\WebApplication1\wwwroot\pic\
                var dir = $"{_env.WebRootPath}";
                //354535-3425435-225-234_2.jpeg
                relativePath = $"/pic/{Guid.NewGuid()}_{model.File.FileName}";


                using (var fs = new FileStream(dir + relativePath, FileMode.Create))
                {
                    model.File.CopyTo(fs);
                }
            }
            _db.Stuednts.Add(new Stuednts
            {
                Email = model.Email,
                Gender = model.Gender,
                Name = model.Name,
                Password = model.Password,
                Phone = model.Phone,
                PicturePath = relativePath
            });
            _db.SaveChanges();
            return RedirectToAction("index", "home");
        }

        [HttpPost]
        public string Login(LoginModel model)
        {
            //if (string.IsNullOrEmpty(model.Account)|| string.IsNullOrEmpty(model.Password))
            //{
            //    return "帳號或密碼失敗";
            //}
            if (!ModelState.IsValid)
            {
                var temp = ModelState.SelectMany(x => x.Value.Errors.Select(z => z.ErrorMessage));
                return string.Join(", ", temp);
                //return "帳號或密碼失敗";
            }


            return model.Account + model.Password;
        }
    }

    public class LoginModel
    {
        [Required(ErrorMessage = "帳號不填是在三小")]
        public string? Account { get; set; }
        [Required(ErrorMessage = "密碼不填是在哈囉")]
        public string? Password { get; set; }
    }
}

WebApplication1/Views/Shared/_HeaderPartial.cshtml
@model HeaderViewModel

<header>
    <h1 class="site-heading text-center text-faded d-none d-lg-block">
        <span class="site-heading-upper text-primary mb-3">@Model.SubTitle</span>
        <span class="site-heading-lower">@Model.Title</span>
    </h1>
</header>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
        <a class="navbar-brand text-uppercase fw-bold d-lg-none" asp-controller="coffee" asp-action="home">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto">
                @{
                    foreach (var menu in Model.Menus)
                    {
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase" asp-controller="@menu.ControllerName" asp-action="@menu.ActionName">@menu.DisplayText</a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
</nav>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles",false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="coffee" asp-action="home">Reds</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="THM104" asp-action="CustomersDisplay">CustomersDisplay</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="THM104" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="THM104" asp-action="students">students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="account" asp-action="logout">登出</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <partial name="_ValidationScriptsPartial" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/css/styles.css" rel="stylesheet" />
</head>
<body>
    @* @Html.Partial("_HeaderPartial") *@
    <partial name="_HeaderPartial" model="@TempData["HeaderData"]" />
    <div>
        @RenderBody()
    </div>
    <footer class="footer text-faded text-center py-5">
        <div class="container"><p class="m-0 small">Copyright &copy; Your Website 2023</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="/js/scripts.js"></script>
    @await RenderSectionAsync("Scripts",false)
</body>
</html>